# Generated by Django 5.1.2 on 2024-12-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='imagename',
        ),
    ]
